### PR TITLE
Some new translations to pt_BR

### PR DESCRIPTION
**Pull request by ArthurBacci64**

### CODE REVIEW

**Comment by maoschanz** [comment]
(you don't have to restart the whole process, you can just do a new commit and push it, it'll end up here in the pull request)

**Comment by ArthurBacci64** [comment]
> Thank you very much, but i see many strings still marked as "fuzzy"
> 
> This occurs when a similar string was already translated: the software producing the po file pre-filled the translations with these approximations ("No options"/"No outline" for example), and you have corrected them but the "fuzzy" tags are still here: could you remove the tags when the translation is correct?
> 
> If you're using GTranslator they can be removed using the button with little waves in the header, if you're using POedit it's a button to toggle at the right of the input

ok, I am doing some other translations and I will do this in the next commit, thank you.

**Comment by ArthurBacci64** [comment]
> (you don't have to restart the whole process, you can just do a new commit and push it, it'll be added to the pull request here)

Done

**Comment by maoschanz** [comment]
Perfect, thank you!

**Pull request merged**
