### PR TITLE
update it.po

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by maoschanz** [comment]
could you fix the string with the wrongly positionned quotation mark, and remove the "fuzzy"s where it's no more fuzzy please?

**Comment by maoschanz** [comment]
>**where it's no more fuzzy**

the "fuzzy" entries are "guessed" by the program generating the file based on the existing translations, they can be right but they are often not exact.

For example the file already contained "No options" (translated as "Nessuna opzione"), and then a new string ("Font options") appeared. It puts "Nessuna opzione" as a fuzzy translation for "Font options" to help you with similar strings: it's often not correct, and needs to be reviewed by the translator.

Fuzzy translations are **not compiled** to avoid wrong translations, so these parts of the UI stay untranslated from an user's point of view until a translator review the file and decide whether a guess is correct and the "fuzzy" tag can be removed without further modification *(here "Opzioni avanzate" or "Elimina la selezione" for example)*, or not *(translating both "Secondary color rectangle" and "Secondary color shadow" as "Colore secondario" would lead to a really confusing "background" section in the font options menu, if you don't fix the translated strings then the tags have to stay)*

**Comment by maoschanz** [comment]
thank you!

**Comment by albanobattistella** [comment]
thanks to you for your great work!
Regards,
Albano

**Pull request merged**
