### PR TITLE
Fixes arrow head

### PR DESCRIPTION
**Pull request by ericvoid**
The "Line" tool with "Arrow" option enabled is glitchy. As you drag the line around, the arrow head deforms according to the angle and the length of the line.

This PR fixes the drawing of the arrow head by using trigonometry. The size of the arrow head scales by the thickness of the line.

And also, when "Use dashes" is used with "Arrow", the dashed line was being overwritten. This PR also fixes this.

The following image was drawn using the fixed version:

image

### CODE REVIEW

**Comment by maoschanz** [comment]
>As you drag the line around, the arrow head deforms according to the angle and the length of the line.

It was intentional, because the very short arrows look weird otherwise. I already started a branch to fix that a few days ago, but you were quicker than me to finish

Can you post a screenshot of an arrow drawn in a semi-transparent color? (it'll be ugly but don't worry it's not a regression)

**Comment by ericvoid** [comment]
Oh, I didn't think about that.

image

That's pretty ugly. It seems it will be specially complicated to fix the dashed line case.

**Comment by ericvoid** [comment]
I my implementation, when you draw short lines this happens:

image

**Comment by maoschanz** [comment]
don't worry about how it looks with semi-transparency, i already have a fix, i just wanted to better see the path you implemented

**Comment by maoschanz** [comment]
So this is related to one of the item of #260 and will be released with 0.6.3

**Pull request merged**
