### PR TITLE
help-overlay: use sentence capitalization

### PR DESCRIPTION
**Pull request by sabriunal**
Use sentence capitalization for the shortcut entries.

### CODE REVIEW

**Comment by sabriunal** [comment]
Important note: It's going to mark all help-overlay entries untranslated.

**Comment by maoschanz** [comment]
>It's going to mark all help-overlay entries untranslated.

it's also going to duplicate them all, which makes me perplex... sorry but the removal of this attribute was on purpose, for various reasons:

For example, translators already localized "undo" in the context of the regular GUI? Translate it again! ...for the shortcut window where it has the same meaning and relates to the same action...? It sounds like a waste of time and effort for translators 😕 i've not added the app on an adequate localization platform yet (#274 ) so their current workflow is a pain in their arse and i don't want to ask them redundant work

---

You may have noticed that i already add context, but manually, using code comments. I avoid using the same words for distinct meanings because the comment for a specific occurrence has to make sense for all occurrences; it's sometimes troublesome to write the english labels because of this, and i can make mistakes while self-reviewing the way it changes the po files. So i see the point of translation contexts, they're designed to help me with this exact kind of work

But i don't think "shortcut window" is a pertinent use of this feature. It's far to generic to be useful as a context, and the problematic strings i encounter are almost never in the shortcut window

- An example of a common problem is a word which is sometimes a verb and sometimes a noun, but both are written the same in english.
- An other case would be actions displayed as "answers" to a question, e.g. in modal dialog windows: "Replace", "Reload", "Cancel", "Apply", etc. here the context is the question and the other possible answers. It's something i strongly care about because in french, both "cancel", "discard", and "undo", can all be translated as "annuler" [which is a traumatic experience when you lost all your work because the actions in a dialog all say the same thing](https://gitlab.gnome.org/GNOME/meld/-/blob/205041d390a3d41cc5033b9c210719e64bf10a46/po/fr.po#L945) (recently fixed but i still have an old version of this app 😭)
- a few words are just used a lot because the app revolves around them (transparency, mosaic, square), and indeed a pencil with a square lead isn't the same as a "square" shape so this is a situation where i should use translation contexts!

But in most situations, words are just used a lot (new image, height, zoom in, anti-aliasing, etc.) because the related feature is referenced in several source files: i think these strings shouldn't be treated as distinct entries. Having each translatable string only once ensures the same notion is translated with a similar label in all contexts, and it helps to ensure UX consistency across the app in my opinion

**Comment by sabriunal** [comment]
Hi @maoschanz, I've removed the context part from the pull request. IMHO, it would make sense to unify the keyboard shortcuts enties using sentence capitalization. What do you think?

**Comment by maoschanz** [comment]
which is related to #572 i'll update the menus too this weekend

**Comment by pedropaulosuzuki** [comment]
Wh is "Touch Gestures" the only one with different capitalization tho?

**Pull request merged**
