### PR TITLE
Makes build process more simple

### PR DESCRIPTION
**Pull request by sudo-give-me-coffee**

### CODE REVIEW

**Comment by maoschanz** [comment]
sorry but Ubuntu 18.04 has a bigger issue than its meson version, which is their python3-gi version not allowing the use of `Gtk.Template`. With your modification you can build the app but not run it.

The branch 0.4 can already be built from source, does not use `Gtk.Template`, and it's the branch people are supposed to package and use. If you want to build the app for contributing to development, i suggest to just use GNOME Builder with the flatpak SDK: the build process can't be more simple (click on the "run" button)

The hacks to make the app compatible with 18.04 will be ported to the branch 0.6 when such a branch will exist, but will not be added to master since i consider them to be regressions

**Comment by sudo-give-me-coffee** [comment]
Python3-gi with support for Gtk.template can be easily installed with a .deb even on Ubuntu 16.04. As for the flatpak builder it creates an overhead of 2 GB (3 if the developer is going to contribute to a single project), it is not very inviting

**Comment by maoschanz** [comment]
Finding, downloading and manually installing untested debs from other versions is easy and inviting, but installing in one click a 100% reusable (well tested, without side-effects, easy to uninstall afterwards) cross-distros SDK isn't? 🤨

I'd like to keep the build logs clean and readable so it's easier for me to notice useful errors and warnings, which is sadly not the case when dozens of useless deprecation warnings are thrown because of the required meson version. Contributors whose hard drives are too small for the 2GB SDK should upgrade to a recent Ubuntu or do manually your modification. I'll update the "CONTRIBUTING.md" to add explanations about the build process and i'll add your remarks to it

**Comment by sudo-give-me-coffee** [comment]
> I'd like to keep the build logs clean and readable so it's easier for me to notice useful errors and warnings, which is sadly not the case when dozens of useless deprecation warnings are thrown because of the required meson version.

The syntax of your meson build isn't for 0.5x but for 0.4x so is more probably your getting deprecation warning for next versions (above 0.5x) than 0.4x

> Finding, downloading and manually installing untested debs from other versions is easy and inviting, but installing in one click a 100% reusable (well tested, without side-effects, easy to uninstall afterwards) cross-distros SDK isn't? 🤨

The main issue is duplication of files by flatpak

**Comment by maoschanz** [comment]
>The syntax of your meson build isn't for 0.5x but for 0.4x so is more probably your getting deprecation warning for next versions (above 0.5x) than 0.4x

Regardless of the branch, when i put a meson version >0.48 there is no warning, and when i don't i have warnings. No "probably" here: this file will stay unchanged for now, and if i get these warnings again in the future the version will even get incremented. Then, meson throwing meaningless deprecation warnings is a valid issue (already reported by others), but that's for the meson maintainers (and as you can guess no one is motivated to contribute to 2 years old versions of meson just to remove a stupid warning).

`CONTRIBUTING.md` will explain that it's fine to change it if a contributor wants to build the master branch, AND use an old distro release, AND prefer a frankendebian to a reproductible dev environment. But such a specific case will not be merged on master

>The main issue is duplication of files by flatpak



i forgot hard drives and SSD were so small nowadays we can't afford reliable and reproductible dev environments.

**Pull request closed without merging**
